[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = "^2.8"
serde = { version = "1.0", features = ["derive"] }
rand = "^0.8"